
category = {
    "movies":    ["Avatar",
                  "Pirates of the Caribbean",
                  "Spectre",
                  "The Dark Knight Rises",
                  "John Carter",
                  "Spider-Man 3",
                  "Tangled",
                  "Avengers: Age of Ultron",
                  "Harry Potter and the Half-Blood Prince",
                  "Batman v Superman: Dawn of Justice",
                  "Superman Returns",
                  "Quantum of Solace",
                  "Pirates of the Caribbean: Dead Man's Chest",
                  "The Lone Ranger",
                  "Man of Steel",
                  "The Chronicles of Narnia",
                  "The Avengers",
                  "Men in Black 3",
                  "The Hobbit",
                  "The Amazing Spider-Man",
                  "Robin Hood",
                  "The Hobbit",
                  "The Golden Compass",
                  "King Kong",
                  "Titanic",
                  "Captain America",
                  "Battleship",
                  "Jurassic World",
                  "Skyfall" ],

    "capitals cities": [
        "Abu Dhabi", "Addis Ababa", "Amman", "Ankara", "Astana", "Athens", "Bangkok", "Beijing",
        "Berlin", "Bern", "Brasília", "Brussels", "Budapest", "Cairo", "Canberra", "Caracas",
        "Colombo", "Copenhagen", "Dakar", "Damascus", "Dublin", "Hanoi", "Havana", "Helsinki",
        "Islamabad", "Jakarta", "Kabul", "Kathmandu", "Kiev", "Kingston", "Kuala Lumpur", "Lima",
        "Lisbon", "London", "Madrid", "Manila", "Mexico City", "Moscow", "Nairobi", "New Delhi",
        "Nicosia", "Oslo", "Ottawa", "Paris", "Pretoria", "Prague", "Quito", "Rabat", "Riyadh",
        "Rome", "San José", "San Salvador", "Santiago", "Sarajevo", "Seoul", "Singapore", "Skopje",
        "Stockholm", "Tallinn", "Tashkent", "Tbilisi", "Tokyo", "Tripoli", "Tunis", "Vienna", "Warsaw",
        "Washington, D.C.", "Wellington", "Windhoek", "Yaoundé", "Zagreb"
    ],

    "sports": [
        "Football", "Basketball", "Tennis", "Baseball", "Cricket", "Soccer", "Golf", "Rugby",
        "Swimming", "Athletics", "Volleyball", "Hockey", "Badminton", "Table Tennis", "Cycling",
        "Boxing", "Wrestling", "Gymnastics", "Skiing", "Snowboarding", "Surfing", "Martial Arts",
        "Weightlifting", "Archery", "Canoeing", "Kayaking", "Sailing", "Diving", "Fencing",
        "Handball", "Softball", "Squash", "Shooting", "Horse Racing", "Racing", "Bowling",
        "Figure Skating", "Taekwondo", "Karate", "Judo", "Polo", "Rowing", "Snooker", "Billiards",
        "Rock Climbing", "Mountaineering", "Ultimate Frisbee", "Bungee Jumping", "Parkour",
        "Water Polo", "Paddleboarding"
    ],
}
